package com.ies.mapper;

import com.ies.domain.Collect;
import com.ies.domain.CollectCriteria;
import java.util.List;

import com.ies.vo.CollectVo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    int countByExample(CollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    int deleteByExample(CollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    int insert(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    int insertSelective(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    List<Collect> selectByExampleWithRowbounds(CollectCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    List<Collect> selectByExample(CollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    Collect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") Collect record, @Param("example") CollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    int updateByExample(@Param("record") Collect record, @Param("example") CollectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    int updateByPrimaryKeySelective(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Sat Mar 28 21:58:36 CST 2020
     */
    int updateByPrimaryKey(Collect record);

    Long queryAllCollectCount(CollectVo collectVo);

    List<Collect> queryAllCollect(CollectVo collectVo);
}