package com.ies.mapper;

import com.ies.domain.Judgment;
import com.ies.domain.JudgmentCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface JudgmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    int countByExample(JudgmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    int deleteByExample(JudgmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    int insert(Judgment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    int insertSelective(Judgment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    List<Judgment> selectByExampleWithRowbounds(JudgmentCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    List<Judgment> selectByExample(JudgmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    Judgment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") Judgment record, @Param("example") JudgmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    int updateByExample(@Param("record") Judgment record, @Param("example") JudgmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    int updateByPrimaryKeySelective(Judgment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    int updateByPrimaryKey(Judgment record);
}