package com.ies.mapper;

import com.ies.domain.Log;
import com.ies.domain.LogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    int countByExample(LogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    int deleteByExample(LogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    List<Log> selectByExampleWithRowbounds(LogCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    List<Log> selectByExample(LogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    Log selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Log record, @Param("example") LogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    int updateByPrimaryKeySelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sat Mar 28 19:57:03 CST 2020
     */
    int updateByPrimaryKey(Log record);
}