package com.ies.mapper;

import com.ies.domain.Player;
import com.ies.domain.PlayerCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface PlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    int countByExample(PlayerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    int deleteByExample(PlayerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    int insert(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    int insertSelective(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    List<Player> selectByExampleWithRowbounds(PlayerCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    List<Player> selectByExample(PlayerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    Player selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") Player record, @Param("example") PlayerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    int updateByExample(@Param("record") Player record, @Param("example") PlayerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    int updateByPrimaryKeySelective(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    int updateByPrimaryKey(Player record);
}