package com.ies.mapper;

import com.ies.domain.VideosType;
import com.ies.domain.VideosTypeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VideosTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    int countByExample(VideosTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    int deleteByExample(VideosTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    int insert(VideosType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    int insertSelective(VideosType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    List<VideosType> selectByExampleWithRowbounds(VideosTypeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    List<VideosType> selectByExample(VideosTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    VideosType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") VideosType record, @Param("example") VideosTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    int updateByExample(@Param("record") VideosType record, @Param("example") VideosTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    int updateByPrimaryKeySelective(VideosType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    int updateByPrimaryKey(VideosType record);
}