package com.ies.mapper;

import com.ies.domain.Watch;
import com.ies.domain.WatchCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    int countByExample(WatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    int deleteByExample(WatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    int insert(Watch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    int insertSelective(Watch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    List<Watch> selectByExampleWithRowbounds(WatchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    List<Watch> selectByExample(WatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    Watch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") Watch record, @Param("example") WatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    int updateByExample(@Param("record") Watch record, @Param("example") WatchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    int updateByPrimaryKeySelective(Watch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    int updateByPrimaryKey(Watch record);
}