package com.ies.domain;

import java.io.Serializable;

public class Judgment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgment.id
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgment.user_id
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgment.name
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgment.phone
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgment.age
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgment.sex
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgment.work_year
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    private Integer workYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judgment.info
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgment.id
     *
     * @return the value of judgment.id
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgment.id
     *
     * @param id the value for judgment.id
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgment.user_id
     *
     * @return the value of judgment.user_id
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgment.user_id
     *
     * @param userId the value for judgment.user_id
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgment.name
     *
     * @return the value of judgment.name
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgment.name
     *
     * @param name the value for judgment.name
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgment.phone
     *
     * @return the value of judgment.phone
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgment.phone
     *
     * @param phone the value for judgment.phone
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgment.age
     *
     * @return the value of judgment.age
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgment.age
     *
     * @param age the value for judgment.age
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgment.sex
     *
     * @return the value of judgment.sex
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgment.sex
     *
     * @param sex the value for judgment.sex
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgment.work_year
     *
     * @return the value of judgment.work_year
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public Integer getWorkYear() {
        return workYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgment.work_year
     *
     * @param workYear the value for judgment.work_year
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public void setWorkYear(Integer workYear) {
        this.workYear = workYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judgment.info
     *
     * @return the value of judgment.info
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judgment.info
     *
     * @param info the value for judgment.info
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judgment
     *
     * @mbggenerated Fri Mar 06 22:59:14 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", phone=").append(phone);
        sb.append(", age=").append(age);
        sb.append(", sex=").append(sex);
        sb.append(", workYear=").append(workYear);
        sb.append(", info=").append(info);
        sb.append("]");
        return sb.toString();
    }
}