package com.ies.domain;

import java.io.Serializable;

public class Player implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.id
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.user_id
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.name
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.phone
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.age
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.idcard
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.sex
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.qq
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.color
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.user_id
     *
     * @return the value of player.user_id
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.user_id
     *
     * @param userId the value for player.user_id
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.name
     *
     * @return the value of player.name
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.name
     *
     * @param name the value for player.name
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.phone
     *
     * @return the value of player.phone
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.phone
     *
     * @param phone the value for player.phone
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.age
     *
     * @return the value of player.age
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.age
     *
     * @param age the value for player.age
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.idcard
     *
     * @return the value of player.idcard
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.idcard
     *
     * @param idcard the value for player.idcard
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.sex
     *
     * @return the value of player.sex
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.sex
     *
     * @param sex the value for player.sex
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.qq
     *
     * @return the value of player.qq
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.qq
     *
     * @param qq the value for player.qq
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.color
     *
     * @return the value of player.color
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.color
     *
     * @param color the value for player.color
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Fri Mar 06 00:18:14 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", phone=").append(phone);
        sb.append(", age=").append(age);
        sb.append(", idcard=").append(idcard);
        sb.append(", sex=").append(sex);
        sb.append(", qq=").append(qq);
        sb.append(", color=").append(color);
        sb.append("]");
        return sb.toString();
    }
}