package com.ies.domain;

import java.io.Serializable;
import java.util.Date;

public class VideosType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_type.id
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_type.name
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_type.created
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_type.id
     *
     * @return the value of video_type.id
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_type.id
     *
     * @param id the value for video_type.id
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_type.name
     *
     * @return the value of video_type.name
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_type.name
     *
     * @param name the value for video_type.name
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_type.created
     *
     * @return the value of video_type.created
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_type.created
     *
     * @param created the value for video_type.created
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type
     *
     * @mbggenerated Sat Mar 28 18:08:50 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", created=").append(created);
        sb.append("]");
        return sb.toString();
    }
}