package com.ies.domain;

import java.io.Serializable;

public class VideoTypeBridge implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_type_bridge.id
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_type_bridge.video_id
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    private Integer videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_type_bridge.video_type_id
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    private Integer videoTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_type_bridge
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_type_bridge.id
     *
     * @return the value of video_type_bridge.id
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_type_bridge.id
     *
     * @param id the value for video_type_bridge.id
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_type_bridge.video_id
     *
     * @return the value of video_type_bridge.video_id
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_type_bridge.video_id
     *
     * @param videoId the value for video_type_bridge.video_id
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_type_bridge.video_type_id
     *
     * @return the value of video_type_bridge.video_type_id
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    public Integer getVideoTypeId() {
        return videoTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_type_bridge.video_type_id
     *
     * @param videoTypeId the value for video_type_bridge.video_type_id
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    public void setVideoTypeId(Integer videoTypeId) {
        this.videoTypeId = videoTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_type_bridge
     *
     * @mbggenerated Sat Mar 28 21:59:14 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", videoId=").append(videoId);
        sb.append(", videoTypeId=").append(videoTypeId);
        sb.append("]");
        return sb.toString();
    }
}