package com.ies.domain;

import java.io.Serializable;
import java.util.Date;

public class Video implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.name
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.descs
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.path
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.created
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.user_id
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.name
     *
     * @return the value of video.name
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.name
     *
     * @param name the value for video.name
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.descs
     *
     * @return the value of video.descs
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.descs
     *
     * @param descs the value for video.descs
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.path
     *
     * @return the value of video.path
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.path
     *
     * @param path the value for video.path
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.created
     *
     * @return the value of video.created
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.created
     *
     * @param created the value for video.created
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.user_id
     *
     * @return the value of video.user_id
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.user_id
     *
     * @param userId the value for video.user_id
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated Tue Mar 31 13:24:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", descs=").append(descs);
        sb.append(", path=").append(path);
        sb.append(", created=").append(created);
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}