package com.ies.domain;

import java.io.Serializable;
import java.util.Date;

public class Watch implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch.id
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch.user_id
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch.video_id
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    private Integer videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch.created
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch.time
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch.id
     *
     * @return the value of watch.id
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch.id
     *
     * @param id the value for watch.id
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch.user_id
     *
     * @return the value of watch.user_id
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch.user_id
     *
     * @param userId the value for watch.user_id
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch.video_id
     *
     * @return the value of watch.video_id
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch.video_id
     *
     * @param videoId the value for watch.video_id
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch.created
     *
     * @return the value of watch.created
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch.created
     *
     * @param created the value for watch.created
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch.time
     *
     * @return the value of watch.time
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch.time
     *
     * @param time the value for watch.time
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watch
     *
     * @mbggenerated Thu Apr 02 02:08:08 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", videoId=").append(videoId);
        sb.append(", created=").append(created);
        sb.append(", time=").append(time);
        sb.append("]");
        return sb.toString();
    }
}